# Generated by Django 5.0.1 on 2024-09-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Programming & Tech', 'Programming & Tech'), ('Graphics & Design', 'Graphics & Design'), ('Digital Marketing', 'Digital Marketing'), ('Writing & Translation', 'Writing & Translation'), ('Video & Animation', 'Video & Animation'), ('Music & Audio', 'Music & Audio'), ('Business', 'Business')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
