# Generated by Django 5.0.1 on 2024-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_delete_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Programming & Tech', 'Programming & Tech'), ('Graphics & Design', 'Graphics & Design'), ('Digital Marketing', 'Digital Marketing'), ('Writing & Translation', 'Writing & Translation'), ('Video & Animation', 'Video & Animation'), ('Music & Audio', 'Music & Audio'), ('Business', 'Business'), ('AI Services', 'AI Services')], max_length=50),
        ),
    ]
