# Generated by Django 5.0.1 on 2024-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categories_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Programming & Tech', 'Programming & Tech'), ('Graphics & Design', 'Graphics & Design'), ('Digital Marketing', 'Digital Marketing'), ('Writing & Translation', 'Writing & Translation'), ('Video & Animation', 'Video & Animation'), ('Music & Audio', 'Music & Audio'), ('Business', 'Business'), ('AI Services', 'AI Services')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
