# Generated by Django 5.0.1 on 2024-09-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_freelancerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='display_name',
        ),
    ]
